## Secret for the fluentd-logzio config
apiVersion: v1
kind: Secret
metadata:
  name: fluentd-logzio
  namespace: kube-logging
type: Opaque
data:
  token: 'YOUR_TOKEN_AS_BASE64'
  type: 'YOUR_TYPE_AS_BASE64'
